version: '3.9'

services:

  api:
    build: .
    container_name: dutyhours-api

    ports:
      - "3000:3000"

    env_file:
      - .env

    depends_on:
      - redis

    command: sh -c "npm run prisma:deploy && npm start"

  worker:
    build: .
    container_name: dutyhours-worker

    env_file:
      - .env

    depends_on:
      - redis

    command: node worker.js

  redis:
    image: redis:7-alpine
    container_name: dutyhours-redis

    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data

volumes:
  redis_data: